name: 'Push to docker'
description: 'Builds packages and pushes a docker image'

inputs:
  github-secret:
    description: 'Github secret'
    required: true
  github-ref-name:
    description: 'Github ref name'
    required: true
  dockerhub-username:
    description: 'Dockerhub username'
    required: true
  dockerhub-token:
    description: 'Dockerhub PAT w/ R+W'
    required: true
  dry-run:
    description: 'dry run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: 'actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955' # ratchet:actions/checkout@v4
      with:
        ref: '${{ inputs.github-ref-name }}'
        fetch-depth: 0
    - name: 'Read github sha'
      id: 'sha'
      shell: 'bash'
      run: |-
        echo "GITHUB_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: 'Install Dependencies'
      shell: 'bash'
      run: 'npm install'
    - name: 'Set up Docker Buildx'
      uses: 'docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435' # ratchet:docker/setup-buildx-action@v3
    - name: 'build'
      shell: 'bash'
      run: 'npm run build'
    - name: 'pack @google/gemini-cli'
      shell: 'bash'
      run: 'npm pack -w @google/gemini-cli --pack-destination ./packages/cli/dist'
    - name: 'pack @google/gemini-cli-core'
      shell: 'bash'
      run: 'npm pack -w @google/gemini-cli-core --pack-destination ./packages/core/dist'
    - name: 'Log in to Dockerhub'
      uses: 'docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1' # ratchet:docker/login-action@v3
      with:
        registry: 'docker.io'
        username: '${{ inputs.dockerhub-username }}'
        password: '${{ inputs.dockerhub-token }}'
    - name: 'Get branch name'
      id: 'branch_name'
      shell: 'bash'
      run: |
        REF_NAME="${{ inputs.github-ref-name }}"
        echo "name=${REF_NAME%/merge}" >> $GITHUB_OUTPUT
    - name: 'Build and Push the Docker Image'
      uses: 'docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83' # ratchet:docker/build-push-action@v6
      if: "${{ inputs.dry-run == 'false' }}"
      with:
        context: '.'
        file: './Dockerfile'
        push: true
        provenance: false # avoid pushing 3 images to Aritfact Registry
        tags: |
          docker.io/google/gemini-cli-sandbox:${{ steps.branch_name.outputs.name }}
          docker.io/google/gemini-cli-sandbox:${{ steps.sha.outputs.GITHUB_SHA }}
    - name: 'Create issue on failure'
      if: |-
        ${{ failure() }}
      shell: 'bash'
      env:
        GITHUB_TOKEN: '${{ inputs.github-secret }}'
        DETAILS_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
      run: |-
        gh issue create \
          --title "Docker build failed" \
          --body "The docker build failed. See the full run for details: ${DETAILS_URL}" \
          --label "kind/bug,release-failure"
